/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "descriptor.pb-c.h"
void   google__protobuf__file_descriptor_set__init
                     (Google__Protobuf__FileDescriptorSet         *message)
{
  static Google__Protobuf__FileDescriptorSet init_value = GOOGLE__PROTOBUF__FILE_DESCRIPTOR_SET__INIT;
  *message = init_value;
}
size_t google__protobuf__file_descriptor_set__get_packed_size
                     (const Google__Protobuf__FileDescriptorSet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__file_descriptor_set__pack
                     (const Google__Protobuf__FileDescriptorSet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__file_descriptor_set__pack_to_buffer
                     (const Google__Protobuf__FileDescriptorSet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FileDescriptorSet *
       google__protobuf__file_descriptor_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FileDescriptorSet *)
     protobuf_c_message_unpack (&google__protobuf__file_descriptor_set__descriptor,
                                allocator, len, data);
}
void   google__protobuf__file_descriptor_set__free_unpacked
                     (Google__Protobuf__FileDescriptorSet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__file_descriptor_proto__init
                     (Google__Protobuf__FileDescriptorProto         *message)
{
  static Google__Protobuf__FileDescriptorProto init_value = GOOGLE__PROTOBUF__FILE_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__file_descriptor_proto__get_packed_size
                     (const Google__Protobuf__FileDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__file_descriptor_proto__pack
                     (const Google__Protobuf__FileDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__file_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__FileDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FileDescriptorProto *
       google__protobuf__file_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FileDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__file_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__file_descriptor_proto__free_unpacked
                     (Google__Protobuf__FileDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__descriptor_proto__extension_range__init
                     (Google__Protobuf__DescriptorProto__ExtensionRange         *message)
{
  static Google__Protobuf__DescriptorProto__ExtensionRange init_value = GOOGLE__PROTOBUF__DESCRIPTOR_PROTO__EXTENSION_RANGE__INIT;
  *message = init_value;
}
void   google__protobuf__descriptor_proto__init
                     (Google__Protobuf__DescriptorProto         *message)
{
  static Google__Protobuf__DescriptorProto init_value = GOOGLE__PROTOBUF__DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__descriptor_proto__get_packed_size
                     (const Google__Protobuf__DescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__descriptor_proto__pack
                     (const Google__Protobuf__DescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__DescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__DescriptorProto *
       google__protobuf__descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__DescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__descriptor_proto__free_unpacked
                     (Google__Protobuf__DescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__field_descriptor_proto__init
                     (Google__Protobuf__FieldDescriptorProto         *message)
{
  static Google__Protobuf__FieldDescriptorProto init_value = GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__field_descriptor_proto__get_packed_size
                     (const Google__Protobuf__FieldDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__field_descriptor_proto__pack
                     (const Google__Protobuf__FieldDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__field_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__FieldDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FieldDescriptorProto *
       google__protobuf__field_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FieldDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__field_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__field_descriptor_proto__free_unpacked
                     (Google__Protobuf__FieldDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__enum_descriptor_proto__init
                     (Google__Protobuf__EnumDescriptorProto         *message)
{
  static Google__Protobuf__EnumDescriptorProto init_value = GOOGLE__PROTOBUF__ENUM_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__enum_descriptor_proto__get_packed_size
                     (const Google__Protobuf__EnumDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__enum_descriptor_proto__pack
                     (const Google__Protobuf__EnumDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__enum_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__EnumDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__EnumDescriptorProto *
       google__protobuf__enum_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__EnumDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__enum_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__enum_descriptor_proto__free_unpacked
                     (Google__Protobuf__EnumDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__enum_value_descriptor_proto__init
                     (Google__Protobuf__EnumValueDescriptorProto         *message)
{
  static Google__Protobuf__EnumValueDescriptorProto init_value = GOOGLE__PROTOBUF__ENUM_VALUE_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__enum_value_descriptor_proto__get_packed_size
                     (const Google__Protobuf__EnumValueDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__enum_value_descriptor_proto__pack
                     (const Google__Protobuf__EnumValueDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__enum_value_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__EnumValueDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__EnumValueDescriptorProto *
       google__protobuf__enum_value_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__EnumValueDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__enum_value_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__enum_value_descriptor_proto__free_unpacked
                     (Google__Protobuf__EnumValueDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__service_descriptor_proto__init
                     (Google__Protobuf__ServiceDescriptorProto         *message)
{
  static Google__Protobuf__ServiceDescriptorProto init_value = GOOGLE__PROTOBUF__SERVICE_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__service_descriptor_proto__get_packed_size
                     (const Google__Protobuf__ServiceDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__service_descriptor_proto__pack
                     (const Google__Protobuf__ServiceDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__service_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__ServiceDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__ServiceDescriptorProto *
       google__protobuf__service_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__ServiceDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__service_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__service_descriptor_proto__free_unpacked
                     (Google__Protobuf__ServiceDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__method_descriptor_proto__init
                     (Google__Protobuf__MethodDescriptorProto         *message)
{
  static Google__Protobuf__MethodDescriptorProto init_value = GOOGLE__PROTOBUF__METHOD_DESCRIPTOR_PROTO__INIT;
  *message = init_value;
}
size_t google__protobuf__method_descriptor_proto__get_packed_size
                     (const Google__Protobuf__MethodDescriptorProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_descriptor_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__method_descriptor_proto__pack
                     (const Google__Protobuf__MethodDescriptorProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_descriptor_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__method_descriptor_proto__pack_to_buffer
                     (const Google__Protobuf__MethodDescriptorProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_descriptor_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__MethodDescriptorProto *
       google__protobuf__method_descriptor_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__MethodDescriptorProto *)
     protobuf_c_message_unpack (&google__protobuf__method_descriptor_proto__descriptor,
                                allocator, len, data);
}
void   google__protobuf__method_descriptor_proto__free_unpacked
                     (Google__Protobuf__MethodDescriptorProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_descriptor_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__file_options__init
                     (Google__Protobuf__FileOptions         *message)
{
  static Google__Protobuf__FileOptions init_value = GOOGLE__PROTOBUF__FILE_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__file_options__get_packed_size
                     (const Google__Protobuf__FileOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__file_options__pack
                     (const Google__Protobuf__FileOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__file_options__pack_to_buffer
                     (const Google__Protobuf__FileOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FileOptions *
       google__protobuf__file_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FileOptions *)
     protobuf_c_message_unpack (&google__protobuf__file_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__file_options__free_unpacked
                     (Google__Protobuf__FileOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__file_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__message_options__init
                     (Google__Protobuf__MessageOptions         *message)
{
  static Google__Protobuf__MessageOptions init_value = GOOGLE__PROTOBUF__MESSAGE_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__message_options__get_packed_size
                     (const Google__Protobuf__MessageOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__message_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__message_options__pack
                     (const Google__Protobuf__MessageOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__message_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__message_options__pack_to_buffer
                     (const Google__Protobuf__MessageOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__message_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__MessageOptions *
       google__protobuf__message_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__MessageOptions *)
     protobuf_c_message_unpack (&google__protobuf__message_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__message_options__free_unpacked
                     (Google__Protobuf__MessageOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__message_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__field_options__init
                     (Google__Protobuf__FieldOptions         *message)
{
  static Google__Protobuf__FieldOptions init_value = GOOGLE__PROTOBUF__FIELD_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__field_options__get_packed_size
                     (const Google__Protobuf__FieldOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__field_options__pack
                     (const Google__Protobuf__FieldOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__field_options__pack_to_buffer
                     (const Google__Protobuf__FieldOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__FieldOptions *
       google__protobuf__field_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__FieldOptions *)
     protobuf_c_message_unpack (&google__protobuf__field_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__field_options__free_unpacked
                     (Google__Protobuf__FieldOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__field_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__enum_options__init
                     (Google__Protobuf__EnumOptions         *message)
{
  static Google__Protobuf__EnumOptions init_value = GOOGLE__PROTOBUF__ENUM_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__enum_options__get_packed_size
                     (const Google__Protobuf__EnumOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__enum_options__pack
                     (const Google__Protobuf__EnumOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__enum_options__pack_to_buffer
                     (const Google__Protobuf__EnumOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__EnumOptions *
       google__protobuf__enum_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__EnumOptions *)
     protobuf_c_message_unpack (&google__protobuf__enum_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__enum_options__free_unpacked
                     (Google__Protobuf__EnumOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__enum_value_options__init
                     (Google__Protobuf__EnumValueOptions         *message)
{
  static Google__Protobuf__EnumValueOptions init_value = GOOGLE__PROTOBUF__ENUM_VALUE_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__enum_value_options__get_packed_size
                     (const Google__Protobuf__EnumValueOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__enum_value_options__pack
                     (const Google__Protobuf__EnumValueOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__enum_value_options__pack_to_buffer
                     (const Google__Protobuf__EnumValueOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__EnumValueOptions *
       google__protobuf__enum_value_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__EnumValueOptions *)
     protobuf_c_message_unpack (&google__protobuf__enum_value_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__enum_value_options__free_unpacked
                     (Google__Protobuf__EnumValueOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__enum_value_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__service_options__init
                     (Google__Protobuf__ServiceOptions         *message)
{
  static Google__Protobuf__ServiceOptions init_value = GOOGLE__PROTOBUF__SERVICE_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__service_options__get_packed_size
                     (const Google__Protobuf__ServiceOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__service_options__pack
                     (const Google__Protobuf__ServiceOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__service_options__pack_to_buffer
                     (const Google__Protobuf__ServiceOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__ServiceOptions *
       google__protobuf__service_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__ServiceOptions *)
     protobuf_c_message_unpack (&google__protobuf__service_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__service_options__free_unpacked
                     (Google__Protobuf__ServiceOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__service_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__method_options__init
                     (Google__Protobuf__MethodOptions         *message)
{
  static Google__Protobuf__MethodOptions init_value = GOOGLE__PROTOBUF__METHOD_OPTIONS__INIT;
  *message = init_value;
}
size_t google__protobuf__method_options__get_packed_size
                     (const Google__Protobuf__MethodOptions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__method_options__pack
                     (const Google__Protobuf__MethodOptions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__method_options__pack_to_buffer
                     (const Google__Protobuf__MethodOptions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__MethodOptions *
       google__protobuf__method_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__MethodOptions *)
     protobuf_c_message_unpack (&google__protobuf__method_options__descriptor,
                                allocator, len, data);
}
void   google__protobuf__method_options__free_unpacked
                     (Google__Protobuf__MethodOptions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__method_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__protobuf__uninterpreted_option__name_part__init
                     (Google__Protobuf__UninterpretedOption__NamePart         *message)
{
  static Google__Protobuf__UninterpretedOption__NamePart init_value = GOOGLE__PROTOBUF__UNINTERPRETED_OPTION__NAME_PART__INIT;
  *message = init_value;
}
void   google__protobuf__uninterpreted_option__init
                     (Google__Protobuf__UninterpretedOption         *message)
{
  static Google__Protobuf__UninterpretedOption init_value = GOOGLE__PROTOBUF__UNINTERPRETED_OPTION__INIT;
  *message = init_value;
}
size_t google__protobuf__uninterpreted_option__get_packed_size
                     (const Google__Protobuf__UninterpretedOption *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__uninterpreted_option__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__uninterpreted_option__pack
                     (const Google__Protobuf__UninterpretedOption *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__uninterpreted_option__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__uninterpreted_option__pack_to_buffer
                     (const Google__Protobuf__UninterpretedOption *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__uninterpreted_option__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__UninterpretedOption *
       google__protobuf__uninterpreted_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__UninterpretedOption *)
     protobuf_c_message_unpack (&google__protobuf__uninterpreted_option__descriptor,
                                allocator, len, data);
}
void   google__protobuf__uninterpreted_option__free_unpacked
                     (Google__Protobuf__UninterpretedOption *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &google__protobuf__uninterpreted_option__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor google__protobuf__file_descriptor_set__field_descriptors[1] =
{
  {
    "file",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorSet, n_file),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorSet, file),
    &google__protobuf__file_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__file_descriptor_set__field_indices_by_name[] = {
  0,   /* field[0] = file */
};
static const ProtobufCIntRange google__protobuf__file_descriptor_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__file_descriptor_set__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FileDescriptorSet",
  "FileDescriptorSet",
  "Google__Protobuf__FileDescriptorSet",
  "google.protobuf",
  sizeof(Google__Protobuf__FileDescriptorSet),
  1,
  google__protobuf__file_descriptor_set__field_descriptors,
  google__protobuf__file_descriptor_set__field_indices_by_name,
  1,  google__protobuf__file_descriptor_set__number_ranges,
  (ProtobufCMessageInit) google__protobuf__file_descriptor_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__file_descriptor_proto__field_descriptors[8] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "package",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, package),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "dependency",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, n_dependency),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, dependency),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "message_type",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, n_message_type),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, message_type),
    &google__protobuf__descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "enum_type",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, n_enum_type),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, enum_type),
    &google__protobuf__enum_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "service",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, n_service),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, service),
    &google__protobuf__service_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "extension",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, n_extension),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, extension),
    &google__protobuf__field_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileDescriptorProto, options),
    &google__protobuf__file_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__file_descriptor_proto__field_indices_by_name[] = {
  2,   /* field[2] = dependency */
  4,   /* field[4] = enum_type */
  6,   /* field[6] = extension */
  3,   /* field[3] = message_type */
  0,   /* field[0] = name */
  7,   /* field[7] = options */
  1,   /* field[1] = package */
  5,   /* field[5] = service */
};
static const ProtobufCIntRange google__protobuf__file_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor google__protobuf__file_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FileDescriptorProto",
  "FileDescriptorProto",
  "Google__Protobuf__FileDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__FileDescriptorProto),
  8,
  google__protobuf__file_descriptor_proto__field_descriptors,
  google__protobuf__file_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__file_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__file_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__descriptor_proto__extension_range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto__ExtensionRange, has_start),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto__ExtensionRange, start),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto__ExtensionRange, has_end),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto__ExtensionRange, end),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__descriptor_proto__extension_range__field_indices_by_name[] = {
  1,   /* field[1] = end */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange google__protobuf__descriptor_proto__extension_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__protobuf__descriptor_proto__extension_range__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.DescriptorProto.ExtensionRange",
  "ExtensionRange",
  "Google__Protobuf__DescriptorProto__ExtensionRange",
  "google.protobuf",
  sizeof(Google__Protobuf__DescriptorProto__ExtensionRange),
  2,
  google__protobuf__descriptor_proto__extension_range__field_descriptors,
  google__protobuf__descriptor_proto__extension_range__field_indices_by_name,
  1,  google__protobuf__descriptor_proto__extension_range__number_ranges,
  (ProtobufCMessageInit) google__protobuf__descriptor_proto__extension_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__descriptor_proto__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "field",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, n_field),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, field),
    &google__protobuf__field_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "nested_type",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, n_nested_type),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, nested_type),
    &google__protobuf__descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "enum_type",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, n_enum_type),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, enum_type),
    &google__protobuf__enum_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "extension_range",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, n_extension_range),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, extension_range),
    &google__protobuf__descriptor_proto__extension_range__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "extension",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, n_extension),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, extension),
    &google__protobuf__field_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__DescriptorProto, options),
    &google__protobuf__message_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__descriptor_proto__field_indices_by_name[] = {
  3,   /* field[3] = enum_type */
  5,   /* field[5] = extension */
  4,   /* field[4] = extension_range */
  1,   /* field[1] = field */
  0,   /* field[0] = name */
  2,   /* field[2] = nested_type */
  6,   /* field[6] = options */
};
static const ProtobufCIntRange google__protobuf__descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor google__protobuf__descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.DescriptorProto",
  "DescriptorProto",
  "Google__Protobuf__DescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__DescriptorProto),
  7,
  google__protobuf__descriptor_proto__field_descriptors,
  google__protobuf__descriptor_proto__field_indices_by_name,
  1,  google__protobuf__descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue google__protobuf__field_descriptor_proto__type__enum_values_by_number[18] =
{
  { "TYPE_DOUBLE", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_DOUBLE", 1 },
  { "TYPE_FLOAT", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_FLOAT", 2 },
  { "TYPE_INT64", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_INT64", 3 },
  { "TYPE_UINT64", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_UINT64", 4 },
  { "TYPE_INT32", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_INT32", 5 },
  { "TYPE_FIXED64", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_FIXED64", 6 },
  { "TYPE_FIXED32", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_FIXED32", 7 },
  { "TYPE_BOOL", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_BOOL", 8 },
  { "TYPE_STRING", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_STRING", 9 },
  { "TYPE_GROUP", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_GROUP", 10 },
  { "TYPE_MESSAGE", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_MESSAGE", 11 },
  { "TYPE_BYTES", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_BYTES", 12 },
  { "TYPE_UINT32", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_UINT32", 13 },
  { "TYPE_ENUM", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_ENUM", 14 },
  { "TYPE_SFIXED32", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_SFIXED32", 15 },
  { "TYPE_SFIXED64", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_SFIXED64", 16 },
  { "TYPE_SINT32", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_SINT32", 17 },
  { "TYPE_SINT64", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_SINT64", 18 },
};
static const ProtobufCIntRange google__protobuf__field_descriptor_proto__type__value_ranges[] = {
{1, 0},{0, 18}
};
const ProtobufCEnumValueIndex google__protobuf__field_descriptor_proto__type__enum_values_by_name[18] =
{
  { "TYPE_BOOL", 7 },
  { "TYPE_BYTES", 11 },
  { "TYPE_DOUBLE", 0 },
  { "TYPE_ENUM", 13 },
  { "TYPE_FIXED32", 6 },
  { "TYPE_FIXED64", 5 },
  { "TYPE_FLOAT", 1 },
  { "TYPE_GROUP", 9 },
  { "TYPE_INT32", 4 },
  { "TYPE_INT64", 2 },
  { "TYPE_MESSAGE", 10 },
  { "TYPE_SFIXED32", 14 },
  { "TYPE_SFIXED64", 15 },
  { "TYPE_SINT32", 16 },
  { "TYPE_SINT64", 17 },
  { "TYPE_STRING", 8 },
  { "TYPE_UINT32", 12 },
  { "TYPE_UINT64", 3 },
};
const ProtobufCEnumDescriptor google__protobuf__field_descriptor_proto__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "google.protobuf.FieldDescriptorProto.Type",
  "Type",
  "Google__Protobuf__FieldDescriptorProto__Type",
  "google.protobuf",
  18,
  google__protobuf__field_descriptor_proto__type__enum_values_by_number,
  18,
  google__protobuf__field_descriptor_proto__type__enum_values_by_name,
  1,
  google__protobuf__field_descriptor_proto__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue google__protobuf__field_descriptor_proto__label__enum_values_by_number[3] =
{
  { "LABEL_OPTIONAL", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__LABEL__LABEL_OPTIONAL", 1 },
  { "LABEL_REQUIRED", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__LABEL__LABEL_REQUIRED", 2 },
  { "LABEL_REPEATED", "GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__LABEL__LABEL_REPEATED", 3 },
};
static const ProtobufCIntRange google__protobuf__field_descriptor_proto__label__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex google__protobuf__field_descriptor_proto__label__enum_values_by_name[3] =
{
  { "LABEL_OPTIONAL", 0 },
  { "LABEL_REPEATED", 2 },
  { "LABEL_REQUIRED", 1 },
};
const ProtobufCEnumDescriptor google__protobuf__field_descriptor_proto__label__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "google.protobuf.FieldDescriptorProto.Label",
  "Label",
  "Google__Protobuf__FieldDescriptorProto__Label",
  "google.protobuf",
  3,
  google__protobuf__field_descriptor_proto__label__enum_values_by_number,
  3,
  google__protobuf__field_descriptor_proto__label__enum_values_by_name,
  1,
  google__protobuf__field_descriptor_proto__label__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor google__protobuf__field_descriptor_proto__field_descriptors[8] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "extendee",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, extendee),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "number",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, has_number),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, number),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "label",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, has_label),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, label),
    &google__protobuf__field_descriptor_proto__label__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, has_type),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, type),
    &google__protobuf__field_descriptor_proto__type__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "type_name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, type_name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "default_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, default_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldDescriptorProto, options),
    &google__protobuf__field_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__field_descriptor_proto__field_indices_by_name[] = {
  6,   /* field[6] = default_value */
  1,   /* field[1] = extendee */
  3,   /* field[3] = label */
  0,   /* field[0] = name */
  2,   /* field[2] = number */
  7,   /* field[7] = options */
  4,   /* field[4] = type */
  5,   /* field[5] = type_name */
};
static const ProtobufCIntRange google__protobuf__field_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor google__protobuf__field_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FieldDescriptorProto",
  "FieldDescriptorProto",
  "Google__Protobuf__FieldDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__FieldDescriptorProto),
  8,
  google__protobuf__field_descriptor_proto__field_descriptors,
  google__protobuf__field_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__field_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__field_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__enum_descriptor_proto__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumDescriptorProto, n_value),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumDescriptorProto, value),
    &google__protobuf__enum_value_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumDescriptorProto, options),
    &google__protobuf__enum_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__enum_descriptor_proto__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = options */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange google__protobuf__enum_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__protobuf__enum_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.EnumDescriptorProto",
  "EnumDescriptorProto",
  "Google__Protobuf__EnumDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__EnumDescriptorProto),
  3,
  google__protobuf__enum_descriptor_proto__field_descriptors,
  google__protobuf__enum_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__enum_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__enum_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__enum_value_descriptor_proto__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "number",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueDescriptorProto, has_number),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueDescriptorProto, number),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueDescriptorProto, options),
    &google__protobuf__enum_value_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__enum_value_descriptor_proto__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = number */
  2,   /* field[2] = options */
};
static const ProtobufCIntRange google__protobuf__enum_value_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__protobuf__enum_value_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.EnumValueDescriptorProto",
  "EnumValueDescriptorProto",
  "Google__Protobuf__EnumValueDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__EnumValueDescriptorProto),
  3,
  google__protobuf__enum_value_descriptor_proto__field_descriptors,
  google__protobuf__enum_value_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__enum_value_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__enum_value_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__service_descriptor_proto__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "method",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceDescriptorProto, n_method),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceDescriptorProto, method),
    &google__protobuf__method_descriptor_proto__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceDescriptorProto, options),
    &google__protobuf__service_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__service_descriptor_proto__field_indices_by_name[] = {
  1,   /* field[1] = method */
  0,   /* field[0] = name */
  2,   /* field[2] = options */
};
static const ProtobufCIntRange google__protobuf__service_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__protobuf__service_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.ServiceDescriptorProto",
  "ServiceDescriptorProto",
  "Google__Protobuf__ServiceDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__ServiceDescriptorProto),
  3,
  google__protobuf__service_descriptor_proto__field_descriptors,
  google__protobuf__service_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__service_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__service_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__method_descriptor_proto__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodDescriptorProto, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "input_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodDescriptorProto, input_type),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "output_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodDescriptorProto, output_type),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "options",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodDescriptorProto, options),
    &google__protobuf__method_options__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__method_descriptor_proto__field_indices_by_name[] = {
  1,   /* field[1] = input_type */
  0,   /* field[0] = name */
  3,   /* field[3] = options */
  2,   /* field[2] = output_type */
};
static const ProtobufCIntRange google__protobuf__method_descriptor_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor google__protobuf__method_descriptor_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.MethodDescriptorProto",
  "MethodDescriptorProto",
  "Google__Protobuf__MethodDescriptorProto",
  "google.protobuf",
  sizeof(Google__Protobuf__MethodDescriptorProto),
  4,
  google__protobuf__method_descriptor_proto__field_descriptors,
  google__protobuf__method_descriptor_proto__field_indices_by_name,
  1,  google__protobuf__method_descriptor_proto__number_ranges,
  (ProtobufCMessageInit) google__protobuf__method_descriptor_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue google__protobuf__file_options__optimize_mode__enum_values_by_number[2] =
{
  { "SPEED", "GOOGLE__PROTOBUF__FILE_OPTIONS__OPTIMIZE_MODE__SPEED", 1 },
  { "CODE_SIZE", "GOOGLE__PROTOBUF__FILE_OPTIONS__OPTIMIZE_MODE__CODE_SIZE", 2 },
};
static const ProtobufCIntRange google__protobuf__file_options__optimize_mode__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex google__protobuf__file_options__optimize_mode__enum_values_by_name[2] =
{
  { "CODE_SIZE", 1 },
  { "SPEED", 0 },
};
const ProtobufCEnumDescriptor google__protobuf__file_options__optimize_mode__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "google.protobuf.FileOptions.OptimizeMode",
  "OptimizeMode",
  "Google__Protobuf__FileOptions__OptimizeMode",
  "google.protobuf",
  2,
  google__protobuf__file_options__optimize_mode__enum_values_by_number,
  2,
  google__protobuf__file_options__optimize_mode__enum_values_by_name,
  1,
  google__protobuf__file_options__optimize_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const protobuf_c_boolean google__protobuf__file_options__java_multiple_files__default_value = 0;
static const Google__Protobuf__FileOptions__OptimizeMode google__protobuf__file_options__optimize_for__default_value = GOOGLE__PROTOBUF__FILE_OPTIONS__OPTIMIZE_MODE__CODE_SIZE;
static const ProtobufCFieldDescriptor google__protobuf__file_options__field_descriptors[5] =
{
  {
    "java_package",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, java_package),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "java_outer_classname",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, java_outer_classname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "optimize_for",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, has_optimize_for),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, optimize_for),
    &google__protobuf__file_options__optimize_mode__descriptor,
    &google__protobuf__file_options__optimize_for__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "java_multiple_files",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, has_java_multiple_files),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, java_multiple_files),
    NULL,
    &google__protobuf__file_options__java_multiple_files__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FileOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__file_options__field_indices_by_name[] = {
  3,   /* field[3] = java_multiple_files */
  1,   /* field[1] = java_outer_classname */
  0,   /* field[0] = java_package */
  2,   /* field[2] = optimize_for */
  4,   /* field[4] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__file_options__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 8, 1 },
  { 999, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor google__protobuf__file_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FileOptions",
  "FileOptions",
  "Google__Protobuf__FileOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__FileOptions),
  5,
  google__protobuf__file_options__field_descriptors,
  google__protobuf__file_options__field_indices_by_name,
  3,  google__protobuf__file_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__file_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean google__protobuf__message_options__message_set_wire_format__default_value = 0;
static const ProtobufCFieldDescriptor google__protobuf__message_options__field_descriptors[2] =
{
  {
    "message_set_wire_format",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MessageOptions, has_message_set_wire_format),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MessageOptions, message_set_wire_format),
    NULL,
    &google__protobuf__message_options__message_set_wire_format__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MessageOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MessageOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__message_options__field_indices_by_name[] = {
  0,   /* field[0] = message_set_wire_format */
  1,   /* field[1] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__message_options__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 999, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__protobuf__message_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.MessageOptions",
  "MessageOptions",
  "Google__Protobuf__MessageOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__MessageOptions),
  2,
  google__protobuf__message_options__field_descriptors,
  google__protobuf__message_options__field_indices_by_name,
  2,  google__protobuf__message_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__message_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue google__protobuf__field_options__ctype__enum_values_by_number[2] =
{
  { "CORD", "GOOGLE__PROTOBUF__FIELD_OPTIONS__CTYPE__CORD", 1 },
  { "STRING_PIECE", "GOOGLE__PROTOBUF__FIELD_OPTIONS__CTYPE__STRING_PIECE", 2 },
};
static const ProtobufCIntRange google__protobuf__field_options__ctype__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex google__protobuf__field_options__ctype__enum_values_by_name[2] =
{
  { "CORD", 0 },
  { "STRING_PIECE", 1 },
};
const ProtobufCEnumDescriptor google__protobuf__field_options__ctype__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "google.protobuf.FieldOptions.CType",
  "CType",
  "Google__Protobuf__FieldOptions__CType",
  "google.protobuf",
  2,
  google__protobuf__field_options__ctype__enum_values_by_number,
  2,
  google__protobuf__field_options__ctype__enum_values_by_name,
  1,
  google__protobuf__field_options__ctype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor google__protobuf__field_options__field_descriptors[3] =
{
  {
    "ctype",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldOptions, has_ctype),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldOptions, ctype),
    &google__protobuf__field_options__ctype__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "experimental_map_key",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldOptions, experimental_map_key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__FieldOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__field_options__field_indices_by_name[] = {
  0,   /* field[0] = ctype */
  1,   /* field[1] = experimental_map_key */
  2,   /* field[2] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__field_options__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 9, 1 },
  { 999, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__protobuf__field_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.FieldOptions",
  "FieldOptions",
  "Google__Protobuf__FieldOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__FieldOptions),
  3,
  google__protobuf__field_options__field_descriptors,
  google__protobuf__field_options__field_indices_by_name,
  3,  google__protobuf__field_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__field_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__enum_options__field_descriptors[1] =
{
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__enum_options__field_indices_by_name[] = {
  0,   /* field[0] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__enum_options__number_ranges[1 + 1] =
{
  { 999, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__enum_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.EnumOptions",
  "EnumOptions",
  "Google__Protobuf__EnumOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__EnumOptions),
  1,
  google__protobuf__enum_options__field_descriptors,
  google__protobuf__enum_options__field_indices_by_name,
  1,  google__protobuf__enum_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__enum_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__enum_value_options__field_descriptors[1] =
{
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__EnumValueOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__enum_value_options__field_indices_by_name[] = {
  0,   /* field[0] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__enum_value_options__number_ranges[1 + 1] =
{
  { 999, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__enum_value_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.EnumValueOptions",
  "EnumValueOptions",
  "Google__Protobuf__EnumValueOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__EnumValueOptions),
  1,
  google__protobuf__enum_value_options__field_descriptors,
  google__protobuf__enum_value_options__field_indices_by_name,
  1,  google__protobuf__enum_value_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__enum_value_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__service_options__field_descriptors[1] =
{
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__ServiceOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__service_options__field_indices_by_name[] = {
  0,   /* field[0] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__service_options__number_ranges[1 + 1] =
{
  { 999, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__service_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.ServiceOptions",
  "ServiceOptions",
  "Google__Protobuf__ServiceOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__ServiceOptions),
  1,
  google__protobuf__service_options__field_descriptors,
  google__protobuf__service_options__field_indices_by_name,
  1,  google__protobuf__service_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__service_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__method_options__field_descriptors[1] =
{
  {
    "uninterpreted_option",
    999,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodOptions, n_uninterpreted_option),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__MethodOptions, uninterpreted_option),
    &google__protobuf__uninterpreted_option__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__method_options__field_indices_by_name[] = {
  0,   /* field[0] = uninterpreted_option */
};
static const ProtobufCIntRange google__protobuf__method_options__number_ranges[1 + 1] =
{
  { 999, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__protobuf__method_options__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.MethodOptions",
  "MethodOptions",
  "Google__Protobuf__MethodOptions",
  "google.protobuf",
  sizeof(Google__Protobuf__MethodOptions),
  1,
  google__protobuf__method_options__field_descriptors,
  google__protobuf__method_options__field_indices_by_name,
  1,  google__protobuf__method_options__number_ranges,
  (ProtobufCMessageInit) google__protobuf__method_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__uninterpreted_option__name_part__field_descriptors[2] =
{
  {
    "name_part",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption__NamePart, name_part),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "is_extension",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption__NamePart, is_extension),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__uninterpreted_option__name_part__field_indices_by_name[] = {
  1,   /* field[1] = is_extension */
  0,   /* field[0] = name_part */
};
static const ProtobufCIntRange google__protobuf__uninterpreted_option__name_part__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__protobuf__uninterpreted_option__name_part__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.UninterpretedOption.NamePart",
  "NamePart",
  "Google__Protobuf__UninterpretedOption__NamePart",
  "google.protobuf",
  sizeof(Google__Protobuf__UninterpretedOption__NamePart),
  2,
  google__protobuf__uninterpreted_option__name_part__field_descriptors,
  google__protobuf__uninterpreted_option__name_part__field_indices_by_name,
  1,  google__protobuf__uninterpreted_option__name_part__number_ranges,
  (ProtobufCMessageInit) google__protobuf__uninterpreted_option__name_part__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__protobuf__uninterpreted_option__field_descriptors[6] =
{
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, n_name),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, name),
    &google__protobuf__uninterpreted_option__name_part__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "identifier_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, identifier_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "positive_int_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, has_positive_int_value),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, positive_int_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "negative_int_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, has_negative_int_value),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, negative_int_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "double_value",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, has_double_value),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, double_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "string_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, has_string_value),
    PROTOBUF_C_OFFSETOF(Google__Protobuf__UninterpretedOption, string_value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned google__protobuf__uninterpreted_option__field_indices_by_name[] = {
  4,   /* field[4] = double_value */
  1,   /* field[1] = identifier_value */
  0,   /* field[0] = name */
  3,   /* field[3] = negative_int_value */
  2,   /* field[2] = positive_int_value */
  5,   /* field[5] = string_value */
};
static const ProtobufCIntRange google__protobuf__uninterpreted_option__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor google__protobuf__uninterpreted_option__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.UninterpretedOption",
  "UninterpretedOption",
  "Google__Protobuf__UninterpretedOption",
  "google.protobuf",
  sizeof(Google__Protobuf__UninterpretedOption),
  6,
  google__protobuf__uninterpreted_option__field_descriptors,
  google__protobuf__uninterpreted_option__field_indices_by_name,
  1,  google__protobuf__uninterpreted_option__number_ranges,
  (ProtobufCMessageInit) google__protobuf__uninterpreted_option__init,
  NULL,NULL,NULL    /* reserved[123] */
};
