#!/usr/bin/env python

import sys

status = 0

line = sys.stdin.readline()
while line:
	line = line[:-1]

	if status == 0:
		if line.startswith("GPBS Protocol"):
			status = 1
			print line
	elif status == 1:
		if line.startswith("    "):
			print line
		else:
			status = 0

	line = sys.stdin.readline()
